### PR TITLE
Delete errors and warnings

### LINKED ISSUE #94: TypeError: Cannot delete property 'onChange' of #<Object>
I'm using it with Material-ui and meteor but it's not working with that error in console.
```
TypeError: Cannot delete property 'onChange' of #<Object>
```

### PR DESCRIPTION
**Pull request by kaw2k**
Fixes #94, #93, #95. 

While I was in the `<Errors />` component, I loosed up the interface from only accepting `string` to `any` for `errors` and `additionalErrors`. This lets users drop anything they want into this component and use `renderError?: (error: any) => React.ReactElement<{}>;` to render them appropriately. 

Yea, this probably should have been two PRs 😁

### CODE REVIEW

File: src/inputs/input.tsx [hunk 1]
```diff
@@ -61,11 +62,12 @@ export default class Input extends React.Component<IInputProps, {}> {
         const hasError = this.props.fieldErrors && this.props.fieldErrors.length;
         const className = `${this.props.className} ${hasError ? 'error' : ''}`;
 
-        let props = this.props;
-        delete props.name;
-        delete props.fieldErrors;
-        delete props.validateOnBlur;
-        delete props.validators;
+        const props = omit([
```
Comment (dehli) [inline src/inputs/input.tsx]: Before you deleted `props.name` and with the change you omit `props.error` instead. Was this intentional?

**Review by dehli — APPROVED** [review]
Looks good to me (as long as the change I commented on was intentional). Is `renderError` backwards compatible? Would it render a string like it did before if it's not passed in?

File: src/inputs/input.tsx (hunk 1 above)
Comment (kaw2k) [inline src/inputs/input.tsx]: Yep 😄! `name` is a vlid html property and we _actually_ want to pass it down to the raw markup as it has semantic meaning. `errors` on the other hand didn't make the cut.

**Comment by xiaohuij** [comment]
I'm working on 0.7.1, encounter warning below, looks like mentioned above.
Warning: Unknown props `showErrorsOnSubmit`, `showErrorsOnChange` on <form> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
[0]     in form (created by Formable)
Warning: Unknown props `errors`, `additionalErrors`, `fieldErrors`, `renderError` on <ul> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
[0]     in ul (created by Errors)
[0]     in Errors (created by EmailEnquiryForm)
Warning: Unknown prop `validators` on <input> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
[0]     in input (created by Input)

Could you please help me out to fix them?  Thank you
